apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: c977e911-3b34-4920-92d3-ad0995e754c8
    subject: custom_a1
    workflow_id: b654317d-c0f1-42e0-97d7-90f8009f45b2
    workflows.argoproj.io/controller-instanceid: c977e911-3b34-4920-92d3-ad0995e754c8
  name: custom-1664288015
  namespace: a1
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: a1
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: rds-instance-reboot-ov7
        template: rds-instance-reboot-ov7
  - container:
      args:
      - kubectl apply -f /tmp/rds-instance-reboot-ov7.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: chaosnative/k8s:2.13.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: rds-instance-reboot-ov7
        path: /tmp/rds-instance-reboot-ov7.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                It injects rds-instance-reboot chaos on RDS cluster
            kind: ChaosExperiment
            metadata:
              name: rds-instance-reboot
              labels:
                name: rds-instance-reboot
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: ci
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name rds-instance-reboot
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: RAMP_TIME
                    value: ""
                  - name: CHAOS_INTERVAL
                    value: "10"
                  - name: LIB
                    value: litmus
                  - name: AWS_SHARED_CREDENTIALS_FILE
                    value: /tmp/cloud_config.yml
                labels:
                  name: rds-instance-reboot
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: ci
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-rds-instance-reboot-ov7.yaml
      - -saveName=/tmp/engine-name
      image: chaosnative/litmus-checker:2.13.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: rds-instance-reboot-ov7
        path: /tmp/chaosengine-rds-instance-reboot-ov7.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: rds-instance-reboot-ov7
              labels:
                workflow_run_id: "{{workflow.uid}}"
                workflow_name: custom-1664288015
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: rds-instance-reboot
                  spec:
                    components:
                      statusCheckTimeouts:
                        delay: 2
                        timeout: 400
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: CLUSTER_NAME
                          value: database-1
                        - name: RDS_INSTANCE_IDENTIFIER
                          value: ""
                        - name: REGION
                          value: us-east-2
                        - name: INSTANCE_AFFECTED_PERC
                          value: "100"
                        - name: SEQUENCE
                          value: parallel
                    probe: []
    metadata:
      labels:
        weight: "10"
    name: rds-instance-reboot-ov7
    outputs: {}
status:
  finishedAt: null
  startedAt: null
