apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 1914a925-8cf3-4b78-914c-aedb8d304be9
    subject: aws-ebs-loss-by-id_litmus
    workflow_id: 3e2f31c4-433b-41b7-a289-e0ffd786e131
    workflows.argoproj.io/controller-instanceid: 1914a925-8cf3-4b78-914c-aedb8d304be9
  name: aws-ebs-loss-by-id-1664258205
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  imagePullSecrets:
  - name: yusdsod
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: ebs-loss-by-id-xta
        template: ebs-loss-by-id-xta
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - container:
      args:
      - kubectl apply -f /tmp/ebs-loss-by-id-xta.yaml -n {{workflow.parameters.adminModeNamespace}}
        && sleep 30
      command:
      - sh
      - -c
      image: docker.io/jonsy13/k8s:2.8.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: ebs-loss-by-id-xta
        path: /tmp/ebs-loss-by-id-xta.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Detaching an ebs volume from ec2 instance for a certain chaos duration.
            kind: ChaosExperiment
            metadata:
              name: ebs-loss-by-id
              labels:
                name: ebs-loss-by-id
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: latest
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - secrets
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: chaosnative/go-runner:ci
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name ebs-loss-by-id
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "30"
                  - name: RAMP_TIME
                    value: ""
                  - name: EBS_VOLUME_ID
                    value: ""
                  - name: REGION
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                  - name: AWS_SHARED_CREDENTIALS_FILE
                    value: /tmp/cloud_config.yml
                  - name: LIB
                    value: litmus
                labels:
                  name: ebs-loss-by-id
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: latest
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-ebs-loss-by-id-xta.yaml
      - -saveName=/tmp/engine-name
      image: docker.io/jonsy13/litmus-checker:2.8.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: ebs-loss-by-id-xta
        path: /tmp/chaosengine-ebs-loss-by-id-xta.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: ebs-loss-by-id-xta
              labels:
                workflow_run_id: "{{workflow.uid}}"
                workflow_name: aws-ebs-loss-by-id-1664258205
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: ebs-loss-by-id
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "30"
                        - name: EBS_VOLUME_ID
                          value: ""
                        - name: REGION
                          value: ""
                    probe: []
    metadata:
      labels:
        weight: "10"
    name: ebs-loss-by-id-xta
    outputs: {}
  - container:
      args:
      - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: docker.io/jonsy13/k8s:2.8.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
