apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 1914a925-8cf3-4b78-914c-aedb8d304be9
    subject: custom-1664212910_litmus
    workflow_id: b7e585d3-e993-4b91-9046-03afce448b3f
    workflows.argoproj.io/controller-instanceid: 1914a925-8cf3-4b78-914c-aedb8d304be9
  name: custom-1664212910
  namespace: litmus
spec:
  concurrencyPolicy: Forbid
  schedule: 16 0-23 * * *
  startingDeadlineSeconds: 0
  timezone: Asia/Calcutta
  workflowMetadata:
    creationTimestamp: null
    labels:
      cluster_id: 1914a925-8cf3-4b78-914c-aedb8d304be9
      workflow_id: b7e585d3-e993-4b91-9046-03afce448b3f
      workflows.argoproj.io/controller-instanceid: 1914a925-8cf3-4b78-914c-aedb8d304be9
  workflowSpec:
    arguments:
      parameters:
      - name: adminModeNamespace
        value: litmus
    entrypoint: custom-chaos
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: argo-chaos
    templates:
    - inputs: {}
      metadata: {}
      name: custom-chaos
      outputs: {}
      steps:
      - - arguments: {}
          name: install-chaos-experiments
          template: install-chaos-experiments
      - - arguments: {}
          name: ecs-container-network-loss-bwi
          template: ecs-container-network-loss-bwi
    - container:
        args:
        - kubectl apply -f /tmp/ecs-container-network-loss-bwi.yaml -n {{workflow.parameters.adminModeNamespace}}
          &&  sleep 30
        command:
        - sh
        - -c
        image: chaosnative/k8s:2.12.0
        name: ""
        resources: {}
      inputs:
        artifacts:
        - name: ecs-container-network-loss-bwi
          path: /tmp/ecs-container-network-loss-bwi.yaml
          raw:
            data: |
              apiVersion: litmuschaos.io/v1alpha1
              description:
                message: |
                  Inject network loss on the aws ecs task containers.
              kind: ChaosExperiment
              metadata:
                name: ecs-container-network-loss
                labels:
                  name: ecs-container-network-loss
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: chaosexperiment
                  app.kubernetes.io/version: latest
              spec:
                definition:
                  scope: Namespaced
                  permissions:
                    - apiGroups:
                        - ""
                      resources:
                        - pods
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - deletecollection
                    - apiGroups:
                        - ""
                      resources:
                        - events
                      verbs:
                        - create
                        - get
                        - list
                        - patch
                        - update
                    - apiGroups:
                        - ""
                      resources:
                        - configmaps
                      verbs:
                        - get
                        - list
                    - apiGroups:
                        - ""
                      resources:
                        - pods/log
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - pods/exec
                      verbs:
                        - get
                        - list
                        - create
                    - apiGroups:
                        - apps
                      resources:
                        - deployments
                        - statefulsets
                        - replicasets
                        - daemonsets
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - apps.openshift.io
                      resources:
                        - deploymentconfigs
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - ""
                      resources:
                        - replicationcontrollers
                      verbs:
                        - get
                        - list
                    - apiGroups:
                        - argoproj.io
                      resources:
                        - rollouts
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - batch
                      resources:
                        - jobs
                      verbs:
                        - create
                        - list
                        - get
                        - delete
                        - deletecollection
                    - apiGroups:
                        - litmuschaos.io
                      resources:
                        - chaosengines
                        - chaosexperiments
                        - chaosresults
                      verbs:
                        - create
                        - list
                        - get
                        - patch
                        - update
                        - delete
                  image: chaosnative/go-runner:ci
                  imagePullPolicy: Always
                  args:
                    - -c
                    - ./experiments -name ecs-container-network-loss
                  command:
                    - /bin/bash
                  env:
                    - name: TOTAL_CHAOS_DURATION
                      value: "30"
                    - name: RAMP_TIME
                      value: ""
                    - name: CHAOS_INTERVAL
                      value: "10"
                    - name: LIB
                      value: litmus
                    - name: DOCUMENT_PATH
                      value: Litmus-AWS-SSM-Docs-For-Network-Loss.yml
                    - name: DOCUMENT_NAME
                      value: Litmus-AWS-SSM-Docs-For-Network-Loss
                    - name: DOCUMENT_FORMAT
                      value: YAML
                    - name: DOCUMENT_TYPE
                      value: Command
                    - name: AWS_SHARED_CREDENTIALS_FILE
                      value: /tmp/cloud_config.yml
                  labels:
                    name: ecs-container-network-loss
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: experiment-job
                    app.kubernetes.io/version: latest
                  secrets:
                    - name: cloud-secret
                      mountPath: /tmp/
      metadata: {}
      name: install-chaos-experiments
      outputs: {}
    - container:
        args:
        - -file=/tmp/chaosengine-ecs-container-network-loss-bwi.yaml
        - -saveName=/tmp/engine-name
        image: chaosnative/litmus-checker:2.12.0
        name: ""
        resources: {}
      inputs:
        artifacts:
        - name: ecs-container-network-loss-bwi
          path: /tmp/chaosengine-ecs-container-network-loss-bwi.yaml
          raw:
            data: |
              apiVersion: litmuschaos.io/v1alpha1
              kind: ChaosEngine
              metadata:
                namespace: "{{workflow.parameters.adminModeNamespace}}"
                generateName: ecs-container-network-loss-bwi
                labels:
                  workflow_run_id: "{{workflow.uid}}"
                  workflow_name: custom-1664212910
              spec:
                engineState: active
                chaosServiceAccount: litmus-admin
                experiments:
                  - name: ecs-container-network-loss
                    spec:
                      components:
                        env:
                          - name: TOTAL_CHAOS_DURATION
                            value: "30"
                          - name: CHAOS_INTERVAL
                            value: "10"
                          - name: CLUSTER_NAME
                            value: ""
                          - name: SERVICE_NAME
                            value: ""
                          - name: REGION
                            value: ""
                          - name: NETWORK_PACKET_LOSS_PERCENTAGE
                            value: "100"
                          - name: INSTALL_DEPENDENCIES
                            value: "True"
                          - name: NETWORK_INTERFACE
                            value: eth0
                          - name: SEQUENCE
                            value: parallel
      metadata:
        labels:
          weight: "10"
      name: ecs-container-network-loss-bwi
      outputs: {}
status:
  active: null
  conditions: null
  lastScheduledTime: null
