---
name: SLSA
on:
  workflow_dispatch:

jobs:
  provenance:
      permissions:
        actions: read # for detecting the Github Actions environment.
        id-token: write # for creating OIDC tokens for signing.
        packages: write # for uploading attestations.
      uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.0.0
      with:
        image: jonsy13/namespace-checker
        digest: sha256:42aae95d06d9bae02b2f1cb71da0cff61d5a221e34a23400ebf06d616f6250f2
        registry-username: ${{ github.actor }}
      secrets:
        registry-password: ${{ secrets.GITHUB_TOKEN }}